apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.serviceName }}.{{ .Values.metadata.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.backendName }}
          servicePort: {{ .Values.ingress.ports.servicePort }}
