apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: {{ .Values.redisMaster.ports.servicePort }}
    targetPort: {{ .Values.redisMaster.ports.servicePort }}
  selector:
    app: redis
    role: master
    tier: backend
